name: Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-style:
    runs-on: ubuntu-latest
    name: Code Style Check
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Pint (Code Style Fixer)
        run: vendor/bin/pint

      - name: Commit and push style fixes
        run: |
          # Configure git
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check if there are any changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing style fixes..."
            
            # Add all changes
            git add .
            
            # Commit changes
            git commit -m "style: fix code style issues" || echo "Nothing to commit"
            
            # Pull latest changes with rebase to handle conflicts
            git pull --rebase origin main || {
              echo "Rebase failed, trying merge instead..."
              git pull origin main --no-rebase || true
            }
            
            # Push changes
            git push origin main
          else
            echo "No changes detected, skipping commit."
          fi
        if: github.event_name == 'push'

      - name: Check if code style is correct
        run: vendor/bin/pint --test